name: build push docker image 
on:
 push:
   branches:
     - dev-branch

jobs:
  build:
   runs-on: self-hosted

   steps:
     - name: checkout github repo 
       uses: actions/checkout@v2 
     - name: login to docker 
       uses: docker/login@v1
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: build a docker image 
       run: docker build -t test-image .
     - name: run docker image 
       run:  docker run -d test-image
     - name: docker tag image 
       run: docker tag test-image:latest betrand1997/test-image:latest 
     - name: push image  
       run: docker push betrand1997/test-image:latest 

