name: build and push docker image 
on:
 push:
   branches:
     - dev-branch 
jobs:
  build:
   runs-on: self-hosted 

   steps:
     - name: checkout githop repo 
       uses: actions/checkout@v2 
     - name: login docker 
       uses: docker/login-action@v2
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: build docker image 
       run: docker build -t new_app . 
     - name: run docker image 
       run: docker run -d -p 7071:70 new_app
     - name: tag image 
       run: docker tag new_app:latest betrand1997/new_app:latest 
     - name: push image 
       run: docker push betrand1997/new_app:latest 
