name: deploy to minikube ok ok 
on: 
 push:
   branches:
     - dev-branch


jobs:
  build:
   runs-on: self-hosted 

   steps:
     - name: actions/checkout 
       uses: actions/checkout@v2 
     - name: deploy to minikube 
       run: | 
        kubectl create -f ./kubernetes/namespace.yaml 
        kubectl create -f ./kubernetes/deployment.yaml 
        kubectl create -f ./kubernetes/service.yaml 
        kubectl get deployment -n dev-namespace 
        kubectl get service -n dev-namespace
       

        kubectl get ns 
  second-job:
    runs-on: self-hosted
    needs: build
    steps:
      - name: port forward 
        run: |
           kubectl port-forward service/myservice 9090:80 -n dev-namespace
            






